# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
        environment:
            POSTGRES_USER: app-user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app

      - image: circleci/redis:5.0.5
    working_directory: ~/sanauth_test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "tests/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt

      - run:
          name: copy test configs
          command:
            mv -f tests/ci/* tests/

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test_results/application/result.xml --cov=src --cov-report=xml --cov-report=html

      - store_test_results:
          path: test_results

      - codecov/upload:
          file: test_results/application/result.xml
